<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
    <LangVersion>latest</LangVersion>
    <AssemblyName>TabInfo</AssemblyName>
    <RootNamespace>TabInfo</RootNamespace>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
  </PropertyGroup>

  <PropertyGroup>
    <RoundsFolder Condition="'$(RoundsFolder)' == ''">/home/bukey/.local/share/Steam/steamapps/common/ROUNDS</RoundsFolder>
    <R2Profile Condition="'$(R2Profile)' == ''">/home/bukey/.var/app/io.github.ebkr.r2modman/config/r2modmanPlus-local/ROUNDS/profiles/Default</R2Profile>
    <Managed>$(RoundsFolder)/ROUNDS_Data/Managed</Managed>
    <BepInExCore>$(R2Profile)/BepInEx/core</BepInExCore>
    <Plugins>$(R2Profile)/BepInEx/plugins</Plugins>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="BepInEx"><HintPath>$(BepInExCore)/BepInEx.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="0Harmony"><HintPath>$(BepInExCore)/0Harmony.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="UnboundLib"><HintPath>$(Plugins)/willis81808-UnboundLib/UnboundLib.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="Assembly-CSharp"><HintPath>$(Managed)/Assembly-CSharp.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="UnityEngine"><HintPath>$(Managed)/UnityEngine.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="UnityEngine.CoreModule"><HintPath>$(Managed)/UnityEngine.CoreModule.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="UnityEngine.UI"><HintPath>$(Managed)/UnityEngine.UI.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="UnityEngine.UIModule"><HintPath>$(Managed)/UnityEngine.UIModule.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="Unity.TextMeshPro"><HintPath>$(Managed)/Unity.TextMeshPro.dll</HintPath><Private>false</Private></Reference>
  </ItemGroup>

  <Target Name="CopyOutputs" AfterTargets="Build">
    <Copy SourceFiles="$(TargetPath)" DestinationFolder="$(MSBuildProjectDirectory)/../package" />
  </Target>
</Project>
